#!/usr/bin/env bash
# Author: Alalilacias
# Description: Helper functions to facilitate interacting with MySQL through Docker
# Version: 0.0.1

MYSQL_CONTAINER="sql-exercises-db"
MYSQL_USER="root"
MYSQL_PASSWORD="password"

mysql_exec_query() {
  local query="$1"
  local database="${2:-}" # optional
  if [[ -n "$database" ]]; then
    docker exec -i "$MYSQL_CONTAINER" mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$database" -e "$query"
  else
    docker exec -i "$MYSQL_CONTAINER" mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "$query"
  fi
}

mysql_exec_file() {
  local file="$1"
  docker exec -i "$MYSQL_CONTAINER" mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" <"$file"
}
